# Generated by Django 4.2.7 on 2024-06-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first_app", "0005_alter_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created", "-updated"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-created", "-updated"]},
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
